version: '3'

services:
  web:
    container_name: node-adminpro
    restart: always
    image: adminpro
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    
  mongo:
    container_name: mongo-adminpro
    image: mongo
    ports: 
      - "27018:27017"
    logging:
      driver: none